{{- range .Values.colors.environments }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    helm:
      parameters:
        - name: image
          value: {{ .image }}
        - name: namespace
          value: {{ .namespace }}
        - name: host
          value: {{ .host }}
    repoURL: https://github.com/joalder/k8s-party-2021
    targetRevision: HEAD
    path: colors
  destination:
    namespace: {{ .namespace }}
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  {{- end}}