argo-cd:
  server:
    ingress:
      tls:
        - hosts:
            - argo-rollouts.meyerzuwestram.net
          secretName: rollout-tls-secret
      enabled: true
      pathType: ImplementationSpecific
      hosts:
        - argo-rollouts.meyerzuwestram.net
    extraArgs:
      - --insecure
