argo-cd:
  server:
    ingress:
      tls:
        - hosts:
            - argocd.meyerzuwestram.net
          secretName: tls-argo-cd
      enabled: true
      pathType: ImplementationSpecific
      hosts:
        - argocd.meyerzuwestram.net
    extraArgs:
      - --insecure
