apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  namespace: {{ .Values.namespace }}
  name: colors
  labels:
    app: colors
spec:
  replicas: 5
  selector:
    matchLabels:
      app: colors
  template:
    metadata:
      labels:
        app: colors
    spec:
      containers:
        - name: colors
          image: {{ .Values.image | default "particule/simplecolorapi:2.0" }}
          ports:
            - name: web
              containerPort: 5000
  strategy:
    canary:
      analysis:
        templates:
          - templateName: webchecks
      steps:
        - setWeight: 20
        - pause:
            duration: "30s"
        - setWeight: 50
        - pause:
            duration: "30s"