apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: webchecks
spec:
  metrics:
    - name: webchecks
      failureLimit: 1
      interval: "5"
      successCondition: result == "ok"
      provider:
        web:
          # paceholders are resolved when an AnalysisRun is created
          url: colors.meyerzuwestram.net
          jsonPath: "{$.status}"